name: CD Pipeline
on:
  workflow_run:
    workflows: ["Create Docker Image"]
    types:
      - completed
jobs:
  runs-on: self-hosted

  steps:
  - name: Pull image from Docker
    run: sudo docker pull munguriek/chucknorris:latest
  - name: Delete old docker container
    run: sudo docker rm -f chucknorris || true
  - name: Run latest docker container
    run: sudo docker run -d -p 8000:8000 --name chucknorris